# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenLoopGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1259, 462)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("font-size: 12pt; font: Arial;")
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 330, 1231, 91))
        self.plainTextEdit.setMouseTracking(True)
        self.plainTextEdit.setStyleSheet("font-size: 15pt; font: Arial;")
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.resetdefaultbutton = QtWidgets.QPushButton(self.centralwidget)
        self.resetdefaultbutton.setGeometry(QtCore.QRect(760, 120, 131, 25))
        self.resetdefaultbutton.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.resetdefaultbutton.setFont(font)
        self.resetdefaultbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(100, 100, 100);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(100, 100, 100);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(200, 200, 200);\n"
"                color: rgb(0, 0, 0);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: rgb(200, 200, 200);\n"
"         \n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"                border-style: inset;\n"
"                }")
        self.resetdefaultbutton.setObjectName("resetdefaultbutton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(600, 10, 321, 101))
        self.frame.setStyleSheet(" color: rgb(0, 0, 0);\n"
" background-color: rgb(255, 255, 255);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.led = QtWidgets.QLabel(self.frame)
        self.led.setGeometry(QtCore.QRect(260, 40, 31, 31))
        self.led.setStyleSheet("\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 12px;\n"
"                border-color: rgb(255, 0, 0);\n"
"         \n"
"                padding: 6px;")
        self.led.setText("")
        self.led.setObjectName("led")
        self.applyacousticbutton = QtWidgets.QPushButton(self.frame)
        self.applyacousticbutton.setGeometry(QtCore.QRect(160, 40, 71, 31))
        self.applyacousticbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(0, 0, 0);\n"
"                border-style: inset;\n"
"            }\n"
"\n"
"         QPushButton:checked {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 2px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(200, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 1px;\n"
"}")
        self.applyacousticbutton.setCheckable(True)
        self.applyacousticbutton.setObjectName("applyacousticbutton")
        self.acousticfreq_spinBox = QtWidgets.QSpinBox(self.frame)
        self.acousticfreq_spinBox.setGeometry(QtCore.QRect(20, 40, 121, 41))
        self.acousticfreq_spinBox.setMaximum(3000000)
        self.acousticfreq_spinBox.setSingleStep(1000)
        self.acousticfreq_spinBox.setProperty("value", 1000000)
        self.acousticfreq_spinBox.setObjectName("acousticfreq_spinBox")
        self.acousticfreqlabel = QtWidgets.QLabel(self.frame)
        self.acousticfreqlabel.setGeometry(QtCore.QRect(30, 10, 201, 21))
        self.acousticfreqlabel.setStyleSheet("")
        self.acousticfreqlabel.setObjectName("acousticfreqlabel")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(160, 10, 431, 141))
        self.frame_2.setStyleSheet(" color: rgb(0, 0, 0);\n"
" background-color: rgb(255, 255, 255);\n"
"font-size: 14pt; font: Arial;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.bxlabel = QtWidgets.QLabel(self.frame_2)
        self.bxlabel.setGeometry(QtCore.QRect(300, 50, 61, 21))
        self.bxlabel.setObjectName("bxlabel")
        self.bzlabel = QtWidgets.QLabel(self.frame_2)
        self.bzlabel.setGeometry(QtCore.QRect(300, 110, 61, 21))
        self.bzlabel.setObjectName("bzlabel")
        self.bylabel = QtWidgets.QLabel(self.frame_2)
        self.bylabel.setGeometry(QtCore.QRect(300, 80, 61, 21))
        self.bylabel.setObjectName("bylabel")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(360, 50, 31, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(360, 80, 31, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(360, 110, 31, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(310, 20, 61, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(30, 10, 131, 21))
        self.label_6.setObjectName("label_6")
        self.manualfieldBx = QtWidgets.QSpinBox(self.frame_2)
        self.manualfieldBx.setGeometry(QtCore.QRect(35, 40, 71, 25))
        self.manualfieldBx.setMinimum(-100)
        self.manualfieldBx.setMaximum(100)
        self.manualfieldBx.setProperty("value", 0)
        self.manualfieldBx.setObjectName("manualfieldBx")
        self.manualfieldBy = QtWidgets.QSpinBox(self.frame_2)
        self.manualfieldBy.setGeometry(QtCore.QRect(35, 70, 71, 25))
        self.manualfieldBy.setMinimum(-100)
        self.manualfieldBy.setMaximum(100)
        self.manualfieldBy.setProperty("value", 0)
        self.manualfieldBy.setDisplayIntegerBase(10)
        self.manualfieldBy.setObjectName("manualfieldBy")
        self.manualfieldBz = QtWidgets.QSpinBox(self.frame_2)
        self.manualfieldBz.setGeometry(QtCore.QRect(35, 100, 71, 25))
        self.manualfieldBz.setMinimum(-100)
        self.manualfieldBz.setMaximum(100)
        self.manualfieldBz.setProperty("value", 0)
        self.manualfieldBz.setDisplayIntegerBase(10)
        self.manualfieldBz.setObjectName("manualfieldBz")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 21, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 21, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 21, 21))
        self.label_9.setObjectName("label_9")
        self.alphadial = QtWidgets.QDial(self.frame_2)
        self.alphadial.setGeometry(QtCore.QRect(140, 10, 81, 81))
        self.alphadial.setMinimum(0)
        self.alphadial.setMaximum(360)
        self.alphadial.setProperty("value", 90)
        self.alphadial.setNotchesVisible(True)
        self.alphadial.setObjectName("alphadial")
        self.alphaspinBox = QtWidgets.QSpinBox(self.frame_2)
        self.alphaspinBox.setGeometry(QtCore.QRect(180, 100, 61, 22))
        self.alphaspinBox.setMaximum(360)
        self.alphaspinBox.setProperty("value", 90)
        self.alphaspinBox.setObjectName("alphaspinBox")
        self.manualalphalabel = QtWidgets.QLabel(self.frame_2)
        self.manualalphalabel.setGeometry(QtCore.QRect(130, 100, 41, 16))
        self.manualalphalabel.setObjectName("manualalphalabel")
        self.bzlabel.raise_()
        self.bxlabel.raise_()
        self.bylabel.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.manualfieldBx.raise_()
        self.manualfieldBy.raise_()
        self.manualfieldBz.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.alphadial.raise_()
        self.alphaspinBox.raise_()
        self.manualalphalabel.raise_()
        self.magneticfieldsimlabel = QtWidgets.QLabel(self.centralwidget)
        self.magneticfieldsimlabel.setGeometry(QtCore.QRect(930, 10, 310, 310))
        self.magneticfieldsimlabel.setStyleSheet("background-color: rgb(0,0,0); border:2px solid rgb(255, 0, 0); ")
        self.magneticfieldsimlabel.setText("")
        self.magneticfieldsimlabel.setObjectName("magneticfieldsimlabel")
        self.savedatabutton = QtWidgets.QPushButton(self.centralwidget)
        self.savedatabutton.setGeometry(QtCore.QRect(600, 120, 131, 31))
        self.savedatabutton.setStyleSheet("QPushButton {\n"
"                color: rgb(0, 0, 0);\n"
"                background-color: rgb(255, 255, 0);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 255, 100);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(255, 255, 200);\n"
"                color: rgb(0, 0, 0);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: red;\n"
"                border: 2px solid red;\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"                border-style: inset;\n"
"                }")
        self.savedatabutton.setCheckable(True)
        self.savedatabutton.setObjectName("savedatabutton")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(170, 160, 421, 141))
        self.frame_4.setStyleSheet(" color: rgb(0, 0, 0);\n"
" background-color: rgb(255, 255, 255);\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.psidial = QtWidgets.QDial(self.frame_4)
        self.psidial.setGeometry(QtCore.QRect(30, 10, 91, 101))
        self.psidial.setStyleSheet("QDial\n"
"    {\n"
"        background-color:QLinearGradient( \n"
"            x1: 0.177, y1: 0.004, x2: 0.831, y2: 0.911, \n"
"            stop: 0 white, \n"
"            stop: 0.061 white, \n"
"            stop: 0.066 lightgray, \n"
"            stop: 0.5 #242424, \n"
"            stop: 0.505 #000000,\n"
"            stop: 0.827 #040404,\n"
"            stop: 0.966 #292929,\n"
"            stop: 0.983 #2e2e2e\n"
"        );\n"
"    }")
        self.psidial.setMinimum(1)
        self.psidial.setMaximum(90)
        self.psidial.setSingleStep(5)
        self.psidial.setProperty("value", 90)
        self.psidial.setNotchTarget(10.0)
        self.psidial.setNotchesVisible(True)
        self.psidial.setObjectName("psidial")
        self.gammalabel = QtWidgets.QLabel(self.frame_4)
        self.gammalabel.setGeometry(QtCore.QRect(180, 115, 121, 20))
        self.gammalabel.setObjectName("gammalabel")
        self.psilabel = QtWidgets.QLabel(self.frame_4)
        self.psilabel.setGeometry(QtCore.QRect(40, 115, 91, 21))
        self.psilabel.setObjectName("psilabel")
        self.gammadial = QtWidgets.QDial(self.frame_4)
        self.gammadial.setGeometry(QtCore.QRect(170, 10, 91, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.gammadial.setFont(font)
        self.gammadial.setStyleSheet("QDial {\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0 #1a5276, stop:0.3 #2980b9, stop:0.7 #3498db, stop:1 #1a5276);\n"
"    border: 2px solid #1a5276;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QDial::handle {\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0 #f39c12, stop:0.3 #f1c40f, stop:0.7 #f39c12, stop:1 #f1c40f);\n"
"    border: 2px solid #e67e22;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    margin: -5px;\n"
"}\n"
"")
        self.gammadial.setMaximum(180)
        self.gammadial.setSingleStep(5)
        self.gammadial.setPageStep(10)
        self.gammadial.setProperty("value", 90)
        self.gammadial.setOrientation(QtCore.Qt.Horizontal)
        self.gammadial.setWrapping(False)
        self.gammadial.setNotchTarget(10.0)
        self.gammadial.setNotchesVisible(True)
        self.gammadial.setObjectName("gammadial")
        self.magneticfrequencydial = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.magneticfrequencydial.setGeometry(QtCore.QRect(320, 80, 81, 41))
        self.magneticfrequencydial.setDecimals(2)
        self.magneticfrequencydial.setMaximum(60.0)
        self.magneticfrequencydial.setProperty("value", 10.0)
        self.magneticfrequencydial.setObjectName("magneticfrequencydial")
        self.rollingfrequencylabel = QtWidgets.QLabel(self.frame_4)
        self.rollingfrequencylabel.setGeometry(QtCore.QRect(290, 10, 121, 61))
        self.rollingfrequencylabel.setObjectName("rollingfrequencylabel")
        self.joystickbutton = QtWidgets.QPushButton(self.centralwidget)
        self.joystickbutton.setGeometry(QtCore.QRect(10, 120, 141, 101))
        self.joystickbutton.setStyleSheet("QPushButton {\n"
"                color: rgb(0, 0, 0);\n"
"                background-color: rgb(0, 255, 255);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 255, 255);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"                font: bold 25px;\n"
"            }\n"
"      \n"
"            QPushButton:checked {\n"
"                color: rgb(0, 0, 0);\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 0, 0);\n"
"                font: bold 25px;\n"
"                min-width: 1em;\n"
"              padding-left: 5px;\n"
"                padding-top: 5px;\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(100, 100, 100);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.joystickbutton.setCheckable(True)
        self.joystickbutton.setObjectName("joystickbutton")
        self.manualapplybutton = QtWidgets.QPushButton(self.centralwidget)
        self.manualapplybutton.setGeometry(QtCore.QRect(10, 10, 141, 101))
        self.manualapplybutton.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(0, 0, 0);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(0, 0, 0);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"                font: bold 25px;\n"
"            }\n"
"      \n"
"            QPushButton:checked {\n"
"                color: rgb(0, 0, 0);\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 0, 0);\n"
"                font: bold 25px;\n"
"                min-width: 1em;\n"
"              padding-left: 5px;\n"
"                padding-top: 5px;\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(100, 100, 100);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.manualapplybutton.setCheckable(True)
        self.manualapplybutton.setObjectName("manualapplybutton")
        self.swimradio = QtWidgets.QRadioButton(self.centralwidget)
        self.swimradio.setGeometry(QtCore.QRect(60, 250, 91, 20))
        self.swimradio.setObjectName("swimradio")
        self.rollradio = QtWidgets.QRadioButton(self.centralwidget)
        self.rollradio.setGeometry(QtCore.QRect(60, 230, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.rollradio.setFont(font)
        self.rollradio.setChecked(True)
        self.rollradio.setObjectName("rollradio")
        self.gradient_status_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.gradient_status_checkbox.setGeometry(QtCore.QRect(60, 270, 91, 31))
        self.gradient_status_checkbox.setObjectName("gradient_status_checkbox")
        self.import_excel_actions = QtWidgets.QPushButton(self.centralwidget)
        self.import_excel_actions.setGeometry(QtCore.QRect(660, 160, 181, 41))
        self.import_excel_actions.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255, 255);\n"
"                background-color: rgb(150, 150, 150);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(150, 150 150);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"                font: bold 15px;\n"
"            }\n"
"\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(100, 100, 100);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.import_excel_actions.setCheckable(True)
        self.import_excel_actions.setObjectName("import_excel_actions")
        self.apply_actions = QtWidgets.QPushButton(self.centralwidget)
        self.apply_actions.setGeometry(QtCore.QRect(660, 210, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.apply_actions.setFont(font)
        self.apply_actions.setStyleSheet("QPushButton {\n"
"                color: rgb(255, 255,255);\n"
"                background-color: rgb(255, 0, 255);\n"
"                border-style: outset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 0, 255);\n"
"                min-width: 1em;\n"
"                padding: 6px;\n"
"                font: bold 15px;\n"
"            }\n"
"      \n"
"            QPushButton:checked {\n"
"                color: rgb(0, 0, 0);\n"
"                background-color: rgb(255, 0, 0);\n"
"                border-style: inset;\n"
"                border-width: 3px;\n"
"                border-radius: 10px;\n"
"                border-color: rgb(255, 0, 0);\n"
"                font: bold 16px;\n"
"                min-width: 1em;\n"
"              padding-left: 5px;\n"
"                padding-top: 5px;\n"
"               \n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(100, 100, 100);\n"
"                color: rgb(255, 255, 255);\n"
"                border-color: rgb(100, 100, 100);\n"
"                padding-left: 5px;\n"
"                padding-top: 5px;\n"
"            }")
        self.apply_actions.setCheckable(True)
        self.apply_actions.setObjectName("apply_actions")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiondock = QtWidgets.QAction(MainWindow)
        self.actiondock.setMenuRole(QtWidgets.QAction.NoRole)
        self.actiondock.setObjectName("actiondock")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.resetdefaultbutton.setText(_translate("MainWindow", "Defaults"))
        self.applyacousticbutton.setText(_translate("MainWindow", "Apply"))
        self.acousticfreqlabel.setText(_translate("MainWindow", "Acoustic Frequency"))
        self.bxlabel.setText(_translate("MainWindow", "Bx: 0"))
        self.bzlabel.setText(_translate("MainWindow", "Bz: 0"))
        self.bylabel.setText(_translate("MainWindow", "By: 0"))
        self.label_2.setText(_translate("MainWindow", "mT"))
        self.label_3.setText(_translate("MainWindow", "mT"))
        self.label_4.setText(_translate("MainWindow", "mT"))
        self.label_5.setText(_translate("MainWindow", "Sensor"))
        self.label_6.setText(_translate("MainWindow", "Manual (%)"))
        self.label_7.setText(_translate("MainWindow", "Bx:"))
        self.label_8.setText(_translate("MainWindow", "By:"))
        self.label_9.setText(_translate("MainWindow", "Bz:"))
        self.manualalphalabel.setText(_translate("MainWindow", "Alpha:"))
        self.savedatabutton.setText(_translate("MainWindow", "Save Data"))
        self.gammalabel.setText(_translate("MainWindow", "Gamma: 90"))
        self.psilabel.setText(_translate("MainWindow", "Psi: 90"))
        self.rollingfrequencylabel.setText(_translate("MainWindow", "Magnetic Rotating \n"
"Frequency:"))
        self.joystickbutton.setText(_translate("MainWindow", "Joystick"))
        self.manualapplybutton.setText(_translate("MainWindow", "Apply"))
        self.swimradio.setText(_translate("MainWindow", "Swim"))
        self.rollradio.setText(_translate("MainWindow", "Roll"))
        self.gradient_status_checkbox.setText(_translate("MainWindow", "Gradient"))
        self.import_excel_actions.setText(_translate("MainWindow", "Import Excel Actions"))
        self.apply_actions.setText(_translate("MainWindow", "Apply Excel Actions"))
        self.actiondock.setText(_translate("MainWindow", "dock"))
